plugins {
    id 'com.github.johnrengelman.shadow'

    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modCompileOnly "maven.modrinth:fabrishot:${rootProject.fabrishot_version}"
    modCompileOnly fabricApi.module("fabric-api-base", rootProject.fabric_api_version)

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}

// TODO: infer from fabric.mod.json?!
def supportedVersions = ["1.21.11"]
def versionSupportName = "(Fabric/Quilt 1.21.11+)"

if (System.getenv("MODRINTH_TOKEN")) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = rootProject.modrinth_id
        versionNumber = rootProject.mod_version + "+fabric"
        uploadFile = remapJar
        gameVersions = supportedVersions
        loaders = ["fabric", "quilt"]
        detectLoaders = false
        versionName = rootProject.mod_version + " " + versionSupportName
        changelog = rootProject.ext.changelog
    }

    publish.dependsOn(tasks.named("modrinth"))
}

if (System.getenv("CURSEFORGE_TOKEN")) {
    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = rootProject.curseforge_id_fabric
            releaseType = "release"

            mainArtifact(remapJar) {
                displayName = rootProject.mod_version + " " + versionSupportName
            }
            for (version in supportedVersions) {
                addGameVersion(version)
            }
            addGameVersion("Fabric")
            changelog = rootProject.ext.changelog
            changelogType = "markdown"
        }
    }

    publish.dependsOn(tasks.named("curseforge"))
}

configurations {
    remapJarOutput {
        canBeConsumed = true
        canBeResolved = false
    }
}

artifacts {
    remapJarOutput(remapJar) // For consumption by github release
}