plugins {
    id 'fabric-loom' version '1.15.4'

    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id "com.github.breadmoirai.github-release" version "2.5.2"
    id "org.ajoberstar.grgit" version "5.0.0-rc.3"
    id "maven-publish"
}

String getGitVersion(Project project) {
    if (grgit != null) {
        if (grgit.describe(tags: true) == "${project.mod_version}") {
            return "${project.mod_version}"
        } else {
            var dirty = grgit.status().clean ? "" : "dirty"
            return "${project.mod_version}-dev.${grgit.head().abbreviatedId}+${dirty}"
        }
    } else {
        return "${project.mod_version}-dev.unknown"
    }
}

String getChangelog(String githubUrl) {
    // Get changes since the last tag
    return grgit.log(includes: ["HEAD"], excludes: [
            // Get the last tag, removing the number of commits since the tag and the current HEAD~ hash
            grgit.describe(commit: "HEAD~", tags: true).replaceAll("-\\d+-[a-z0-9]+\$", "")
    ]).collect {
        "- ${it.shortMessage} (${it.author.name})"
    }.join("\n") + (githubUrl == null ? "" : "\n\nSee the full changes on Github: ${githubUrl}commits/${grgit.describe(tags: true)}")
}

ext {
    changelog = getChangelog(project.github_url)
    changelogGithub = getChangelog(null)
}

group = project.maven_group
version = getGitVersion(project)

base {
    archivesName = project.archives_name
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings "net.fabricmc:yarn:$project.yarn_mappings:v2"

    modImplementation "net.fabricmc:fabric-loader:$project.fabric_loader_version"

    modCompileOnly "maven.modrinth:fabrishot:${project.fabrishot_version}"
    modCompileOnly fabricApi.module("fabric-api-base", project.fabric_api_version)

    // This library loads in OSX, but not in Windows - I'm including it here so I can compile on Windows
    implementation "ca.weblite:java-objc-bridge:1.0.0"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

// Publishing
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}

def supportedVersions = ["1.21.11"]
def versionSupportName = "(Fabric/Quilt 1.21.11+)"

if (System.getenv("MODRINTH_TOKEN")) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = project.modrinth_id
        versionNumber = project.mod_version + "+fabric"
        uploadFile = remapJar
        gameVersions = supportedVersions
        loaders = ["fabric", "quilt"]
        detectLoaders = false
        versionName = project.mod_version + " " + versionSupportName
        changelog = project.ext.changelog
    }

    publish.dependsOn(tasks.named("modrinth"))
}

if (System.getenv("CURSEFORGE_TOKEN")) {
    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = project.curseforge_id_fabric
            releaseType = "release"

            mainArtifact(remapJar) {
                displayName = project.mod_version + " " + versionSupportName
            }
            for (ver in supportedVersions) {
                addGameVersion(ver)
            }
            addGameVersion("Fabric")
            changelog = project.ext.changelog
            changelogType = "markdown"
        }
    }

    publish.dependsOn(tasks.named("curseforge"))
}

if (System.getenv("GITHUB_TOKEN")) {
    githubRelease {
        owner = project.github_repo_user
        repo = project.github_repo_name
        tagName = project.mod_version
        releaseName = "Release ${project.mod_version}"
        targetCommitish = "1.21-arch"
        draft = false
        body = project.ext.changelogGithub
        token System.getenv("GITHUB_TOKEN")
        releaseAssets.from(remapJar)
        overwrite = true
    }

    publish.dependsOn(tasks.githubRelease)
}
