# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.12
maven_group = link.infra.screenshotclipboard
archives_name = screenshot-to-clipboard
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.6
yarn_mappings = 1.21.6+build.1

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.128.0+1.21.6
fabrishot_version= 1.14.4
neoforge_version = 21.6.12-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

modrinth_id=1KiJRrTg
curseforge_id_forge=326950
curseforge_id_fabric=327154
github_url=https://github.com/comp500/ScreenshotToClipboard/
github_repo_user=comp500
github_repo_name=ScreenshotToClipboard